services:
  app:
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - EDITOR_EMAIL=${EDITOR_EMAIL}
    volumes:
      - order-data:/app/data
    ports:
      - "4000:3000"

volumes:
  order-data:
